# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clerk < Formula
  desc "Declarative development framework clerk"
  homepage "https://github.com/asweed888/clerk"
  version "0.6.1"

  on_macos do
    url "https://github.com/asweed888/clerk/releases/download/v0.6.1/clerk_darwin_all.tar.gz"
    sha256 "10b6be5e54dfb4035fe08ae177c45253111ee9545a75de2d18e41d3629f61adc"

    def install
      bin.install "clerk"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/asweed888/clerk/releases/download/v0.6.1/clerk_linux_x86_64.tar.gz"
      sha256 "c1d3c27b57ba1df12e9dc0be10ae01dd411db726c6e76faa4dc57994b030ed63"

      def install
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/clerk/releases/download/v0.6.1/clerk_linux_arm64.tar.gz"
      sha256 "83e0134d05fb1c8bf219b7c74c0a03fdd5d725c5b495eb4214978095814ca123"

      def install
        bin.install "clerk"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/asweed888/clerk/releases/download/v0.6.1/clerk_linux_armv6.tar.gz"
      sha256 "dbbc4c8fba35c226aabf849e19cff7d5ca87473f6f0745fb4fb58e08dfe926ae"

      def install
        bin.install "clerk"
      end
    end
  end

  test do
    system "#{bin}/clerk help"
  end
end
